#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS == 'android':
		return

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []
	linkflags = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']
	if bld.env.IOS:
		source += ['SDL_uikit_main.c', 'ios/Launchdiag.m']
		# waf's uselib expansion does not reliably pick these up on the iOS
		# cross build, so pass the frameworks + the Objective-C runtime
		# (objc_msgSend, autoreleasepool, ...) directly as link flags.
		linkflags += [
			'-framework', 'Foundation',
			'-framework', 'UIKit',
			'-framework', 'CoreGraphics',
			'-framework', 'AVFoundation',
			'-lobjc',
		]

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

