#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS == 'android':
		return

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []
	linkflags = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']
	if bld.env.IOS:
		source += ['ios/Launchdiag.m']
		# SDL 2.0.7's static libSDL2.a provides its own iOS main() (in
		# SDL_uikitappdelegate.m) that boots UIApplicationMain and then calls
		# the engine's SDL_main. The launcher_main SDL_uikit_main.c shim is for
		# SDL 2.0.10+ (SDL_UIKitRunApp) and must NOT be compiled here.
		# waf's uselib expansion does not reliably pick these up on the iOS
		# cross build, so pass the frameworks + the Objective-C runtime
		# (objc_msgSend, autoreleasepool, ...) + the static SDL2 lib directly.
		linkflags += [
			'-framework', 'Foundation',
			'-framework', 'UIKit',
			'-framework', 'CoreGraphics',
			'-framework', 'AVFoundation',
			'-framework', 'OpenGLES',
			'-framework', 'QuartzCore',
			'-framework', 'CoreAudio',
			'-framework', 'AudioToolbox',
			'-framework', 'CoreMotion',
			'-framework', 'GameController',
			'-lobjc',
		]
		import os as _os
		_sdl2lib = _os.environ.get('NBC_SDL2_LIB')
		if _sdl2lib:
			linkflags += [ '-L' + _sdl2lib, '-lSDL2' ]

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

